#!/usr/bin/env bash

# This script creates a default directory structure below $HOME.

set -eu

dirs=(
	bin
	scripts
	code
	work/code
	work/documents
)

for dir in ${dirs[@]}; do
	mkdir -vp ~/$dir
done
