[package]
name = "rusty-prompt"
version = "0.1.0"
authors = ["Andreas Linz <klingt.net@gmail.com>"]

[dependencies]
colored = "1"
hostname = "0"
git2 = "0"
libc = "0"
humantime = "1"
dirs = "2"
systemstat = "0"
notify-rust = "3"
