#!/bin/python3

import subprocess
import re
import sys

ticket_re = re.compile(r"(DEV-\d+)$")
rev_parse = subprocess.run(
    ["git", "rev-parse", "--abbrev-ref", "HEAD"], capture_output=True, text=True
).stdout
ticket_match = ticket_re.search(rev_parse)
if not ticket_match:
    exit()
ticket = ticket_match.group()

msg = sys.argv[1]
with open(msg) as f:
    if f.read().find(f"Jira-Ticket: {ticket}") > 0:
        exit()


with open(msg, "a") as f:
    f.write(f"\nJira-Ticket: {ticket}")
